# Generated by Django 4.2.11 on 2024-04-10 16:34
"""Migration module"""
from django.db import migrations


class Migration(migrations.Migration):
    """Migration for our database"""
    dependencies = [
        ('account_holders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
