"""
Database migration file for creating the Booking model.

This migration creates the Booking model.
"""

# Generated by Django 4.2.11 on 2024-04-11 09:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Database migration for creating the Booking model.

    This migration creates the Booking model.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('special_occasion', models.CharField(
                    choices=[
                        ('anniversary', 'Anniversary'),
                        ('date', 'Date'),
                        ('business', 'Business')
                    ],
                    max_length=11
                )),
                ('meal_day', models.DateField()),
                ('meal_time', models.CharField(
                    choices=[],
                    max_length=5
                )),
                ('number_of_guests', models.PositiveIntegerField(
                    null=True,
                    validators=[
                        django.core.validators.MinValueValidator(1),
                        django.core.validators.MaxValueValidator(6)
                    ]
                )),
                ('customer_name', models.CharField(max_length=50)),
                ('name', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
