# Generated by Django 4.2.11 on 2024-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='meal_time',
            field=models.TimeField(),
        ),
    ]
