# Generated by Django 4.2.11 on 2024-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_booked_alter_booking_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_occasion',
            field=models.CharField(choices=[(None, 'none'), ('anniversary', 'Anniversary'), ('date', 'Date'), ('business', 'Business')], max_length=11),
        ),
    ]
