# Generated by Django 4.2.11 on 2024-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_special_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_occasion',
            field=models.CharField(choices=[('None', 'None'), ('anniversary', 'Anniversary'), ('date', 'Date'), ('business', 'Business')], max_length=11),
        ),
    ]
