# Generated by Django 4.2.11 on 2024-05-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_special_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_booked',
        ),
    ]
